#ifndef SOFTSEC_PROJECT_SECTRANS_ACTIONS_H
#define SOFTSEC_PROJECT_SECTRANS_ACTIONS_H

#define ACTION_CREATE 'S'
#define ACTION_ADD 'A'
#define ACTION_DOWNLOAD 'D'
#define ACTION_REMOVE 'R'
#define ACTION_END 'E'
#define ACTION_LIST 'L'

#endif //SOFTSEC_PROJECT_SECTRANS_ACTIONS_H
