#ifndef SOFTSEC_PROJECT_SECTRANS_ACTIONS_H
#define SOFTSEC_PROJECT_SECTRANS_ACTIONS_H

#define ACTION_CREATE "CR"
#define ACTION_ADD "AD"
#define ACTION_DOWNLOAD "DL"
#define ACTION_REMOVE "RM"
#define ACTION_END "EN"
#define ACTION_LIST "LT"
#define ACTION_LOGIN "LG"
#define ACTION_REGISTER "RG"
#define ACTION_REPONSE "RS"

#endif //SOFTSEC_PROJECT_SECTRANS_ACTIONS_H
