#ifndef SOFTSEC_PROJECT_SECTRANS_CONSTANTS_H
#define SOFTSEC_PROJECT_SECTRANS_CONSTANTS_H

#define INPUT_SIZE 1024
#define SERVER_PORT 2000
#define MAX_FILEPATH_SIZE 5120

#endif //SOFTSEC_PROJECT_SECTRANS_CONSTANTS_H
