#ifndef SOFTSEC_PROJECT_SECTRANS_BASE64CONSTANT_H
#define SOFTSEC_PROJECT_SECTRANS_BASE64CONSTANT_H

static const char b64chars[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

#endif //SOFTSEC_PROJECT_SECTRANS_BASE64CONSTANT_H
