#ifndef SOFTSEC_PROJECT_SECTRANS_CLIENT_MESSAGE_MANAGEMENT_H
#define SOFTSEC_PROJECT_SECTRANS_CLIENT_MESSAGE_MANAGEMENT_H

void send_file(char filepath[], int port);

#endif //SOFTSEC_PROJECT_SECTRANS_CLIENT_MESSAGE_MANAGEMENT_H
