/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
void sub_10C0();
// int __fastcall _cxa_finalize(void *);
// char *strncpy(char *dest, const char *src, size_t n);
// int puts(const char *s);
// size_t strlen(const char *s);
// uint16_t htons(uint16_t hostshort);
// ssize_t send(int fd, const void *buf, size_t n, int flags);
// int close(int fd);
// int inet_pton(int af, const char *cp, void *buf);
// int connect(int fd, const struct sockaddr *addr, socklen_t len);
// int socket(int domain, int type, int protocol);
char *(**deregister_tm_clones())(char *dest, const char *src, size_t n);
__int64 register_tm_clones();
char *(**_do_global_dtors_aux())(char *dest, const char *src, size_t n);
__int64 frame_dummy(); // weak
__int64 __fastcall sndmsg(const char *a1, uint16_t a2);
void term_proc();
// char *strncpy(char *dest, const char *src, size_t n);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
char leng[5] = "1025"; // weak
char completed_8060; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
    __int64 (**result)(void); // rax

    result = &_gmon_start__;
    if ( &_gmon_start__ )
        return (__int64 (**)(void))_gmon_start__();
    return result;
}
// 40D8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
    JUMPOUT(0LL);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
    sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
    sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
    sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
    sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
    sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
    sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
    sub_1020();
}

//----- (00000000000010A0) ----------------------------------------------------
void sub_10A0()
{
    sub_1020();
}

//----- (00000000000010B0) ----------------------------------------------------
void sub_10B0()
{
    sub_1020();
}

//----- (00000000000010C0) ----------------------------------------------------
void sub_10C0()
{
    sub_1020();
}

//----- (0000000000001180) ----------------------------------------------------
char *(**deregister_tm_clones())(char *dest, const char *src, size_t n)
{
    return &strncpy;
}

//----- (00000000000011B0) ----------------------------------------------------
__int64 register_tm_clones()
{
    return 0LL;
}

//----- (00000000000011F0) ----------------------------------------------------
char *(**_do_global_dtors_aux())(char *dest, const char *src, size_t n)
{
    char *(**result)(char *, const char *, size_t); // rax

    if ( !completed_8060 )
    {
        if ( &__cxa_finalize )
            _cxa_finalize(_dso_handle);
        result = deregister_tm_clones();
        completed_8060 = 1;
    }
    return result;
}
// 4075: using guessed type char completed_8060;

//----- (0000000000001230) ----------------------------------------------------
__int64 frame_dummy()
{
    return register_tm_clones();
}
// 1230: using guessed type __int64 frame_dummy();

//----- (0000000000001239) ----------------------------------------------------
__int64 __fastcall sndmsg(const char *a1, uint16_t a2)
{
    size_t v3; // rax
    int fd; // [rsp+18h] [rbp-428h]
    struct sockaddr addr; // [rsp+20h] [rbp-420h] BYREF
    char dest[1032]; // [rsp+30h] [rbp-410h] BYREF
    unsigned __int64 v7; // [rsp+438h] [rbp-8h]

    v7 = __readfsqword(0x28u);
    strncpy(dest, a1, 0x400uLL);
    dest[1024] = 0;
    fd = socket(2, 1, 0);
    if ( fd >= 0 )
    {
        addr.sa_family = 2;
        *(_WORD *)addr.sa_data = htons(a2);
        if ( inet_pton(2, "127.0.0.1", &addr.sa_data[2]) > 0 )
        {
            if ( connect(fd, &addr, 0x10u) >= 0 )
            {
                send(fd, leng, 5uLL, 0);
                v3 = strlen(dest);
                send(fd, dest, v3, 0);
                close(fd);
                return 0LL;
            }
            else
            {
                puts("\nConnection Failed ");
                return 0xFFFFFFFFLL;
            }
        }
        else
        {
            puts("\nInvalid address/ Address not supported ");
            return 0xFFFFFFFFLL;
        }
    }
    else
    {
        puts("\n Socket creation error ");
        return 0xFFFFFFFFLL;
    }
}

//----- (00000000000013C8) ----------------------------------------------------
void term_proc()
{
    ;
}

// nfuncs=41 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
