/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
void sub_10C0();
void sub_10D0();
void sub_10E0();
// int __fastcall _cxa_finalize(void *);
// char *strcpy(char *dest, const char *src);
// int setsockopt(int fd, int level, int optname, const void *optval, socklen_t optlen);
// uint16_t htons(uint16_t hostshort);
// int close(int fd);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int listen(int fd, int n);
// int bind(int fd, const struct sockaddr *addr, socklen_t len);
// void perror(const char *s);
// int accept(int fd, struct sockaddr *addr, socklen_t *addr_len);
// int atoi(const char *nptr);
// void __noreturn exit(int status);
// int socket(int domain, int type, int protocol);
char *deregister_tm_clones();
__int64 register_tm_clones();
char *_do_global_dtors_aux();
__int64 frame_dummy(); // weak
int __fastcall startserver(uint16_t a1);
__int64 __fastcall getmsg(char *a1);
__int64 stopserver(); // weak
void term_proc();
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
socklen_t addrlen[2] = { 16u, 0u }; // weak
char completed_8060; // weak
int server_fd[4]; // weak
struct sockaddr address; // weak
_UNKNOWN valread; // weak
_UNKNOWN new_socket; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
    __int64 (**result)(void); // rax

    result = &_gmon_start__;
    if ( &_gmon_start__ )
        return (__int64 (**)(void))_gmon_start__();
    return result;
}
// 4140: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
    JUMPOUT(0LL);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
    sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
    sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
    sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
    sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
    sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
    sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
    sub_1020();
}

//----- (00000000000010A0) ----------------------------------------------------
void sub_10A0()
{
    sub_1020();
}

//----- (00000000000010B0) ----------------------------------------------------
void sub_10B0()
{
    sub_1020();
}

//----- (00000000000010C0) ----------------------------------------------------
void sub_10C0()
{
    sub_1020();
}

//----- (00000000000010D0) ----------------------------------------------------
void sub_10D0()
{
    sub_1020();
}

//----- (00000000000010E0) ----------------------------------------------------
void sub_10E0()
{
    sub_1020();
}

//----- (00000000000011C0) ----------------------------------------------------
char *deregister_tm_clones()
{
    return &completed_8060;
}
// 4090: using guessed type char completed_8060;

//----- (00000000000011F0) ----------------------------------------------------
__int64 register_tm_clones()
{
    return 0LL;
}

//----- (0000000000001230) ----------------------------------------------------
char *_do_global_dtors_aux()
{
    char *result; // rax

    if ( !completed_8060 )
    {
        if ( &__cxa_finalize )
            _cxa_finalize(_dso_handle);
        result = deregister_tm_clones();
        completed_8060 = 1;
    }
    return result;
}
// 4090: using guessed type char completed_8060;

//----- (0000000000001270) ----------------------------------------------------
__int64 frame_dummy()
{
    return register_tm_clones();
}
// 1270: using guessed type __int64 frame_dummy();

//----- (0000000000001279) ----------------------------------------------------
int __fastcall startserver(uint16_t a1)
{
    int result; // eax
    int optval; // [rsp+1Ch] [rbp-4h] BYREF

    optval = 1;
    server_fd[0] = socket(2, 1, 0);
    if ( server_fd[0] < 0 )
    {
        perror("socket failed");
        exit(1);
    }
    if ( setsockopt(server_fd[0], 1, 15, &optval, 4u) )
    {
        perror("setsockopt");
        exit(1);
    }
    address.sa_family = 2;
    *(_DWORD *)&address.sa_data[2] = 0;
    *(_WORD *)address.sa_data = htons(a1);
    if ( bind(server_fd[0], &address, 0x10u) < 0 )
    {
        perror("bind failed");
        exit(1);
    }
    result = listen(server_fd[0], 3);
    if ( result < 0 )
    {
        perror("listen");
        exit(1);
    }
    return result;
}
// 40A0: using guessed type int server_fd[4];
// 40B0: using guessed type struct sockaddr address;

//----- (00000000000013AD) ----------------------------------------------------
__int64 __fastcall getmsg(char *a1)
{
    __int64 buf[128]; // [rsp+10h] [rbp-410h] BYREF
    char v3; // [rsp+410h] [rbp-10h]
    int v4; // [rsp+41Ch] [rbp-4h]

    memset(buf, 0, sizeof(buf));
    v3 = 0;
    new_socket = accept(server_fd[0], &address, addrlen);
    if ( new_socket < 0 )
    {
        perror("accept");
        exit(1);
    }
    valread = read(new_socket, buf, 5uLL);
    v4 = atoi((const char *)buf);
    valread = read(new_socket, buf, v4);
    close(new_socket);
    strcpy(a1, (const char *)buf);
    return 0LL;
}
// 4080: using guessed type socklen_t addrlen[2];
// 40A0: using guessed type int server_fd[4];
// 40B0: using guessed type struct sockaddr address;

//----- (00000000000014DB) ----------------------------------------------------
__int64 stopserver()
{
    close(server_fd[0]);
    return 0LL;
}
// 14DB: using guessed type __int64 stopserver();
// 40A0: using guessed type int server_fd[4];

//----- (00000000000014FC) ----------------------------------------------------
void term_proc()
{
    ;
}

// nfuncs=49 queued=22 decompiled=22 lumina nreq=0 worse=0 better=0
// ALL OK, 22 function(s) have been successfully decompiled
